### ISSUE TITLE
anti-collision deciding to hit children

### ISSUE THREAD

**Issue by ao994** [ao994/cs386-a2.1#1]
Our detection feature for pedestrians and other obstacles is not triggering the car breaks in testing for small obstables such as children or bushes, and is instead hitting them instead of slamming on the breaks. Please advise, does the NN need to be rolled back? Was it trained on bad data?

**Comment by kkarissa** [comment]
It is possible that the software is detecting the children as the roadway and not actual humans. This must be fixed immediately.
